# Configuration for gem-release
bump:
  commit: true
  message: "Bump version to %{version}"
  skip_ci: false
  push: true

tag:
  tag: v%{version}
  sign: true

release:
  host: https://rubygems.org
